package android.example.com.squawker.fcm;

import android.util.Log;

import com.google.firebase.iid.FirebaseInstanceId;
import com.google.firebase.iid.FirebaseInstanceIdService;

/**
 * Created by BappY on 5/9/2017.
 */

// COMPLETED (2) Create a new Service class that extends FirebaseInstanceIdService.

public class SquakFirebaseInsanceIdService extends FirebaseInstanceIdService {

    // Creating the Log Tag for the console
    private static String LOG_TAG = SquakFirebaseInsanceIdService.class.getSimpleName();

    // You'll need to implement the onTokenRefresh method. Simply have it print out
    // the new token.

    @Override
    public void onTokenRefresh() {
        // Get updated FirbaseInstancIdService generated InstanceId token.
        String refreshedToken = FirebaseInstanceId.getInstance().getToken();
        Log.d(LOG_TAG, "Refreshed Token: " +refreshedToken);

        // Now we cn use his token generated by FirebaseInstanceIdService to speceficaally send mssages to that device.
        // inordr to hanlde the server section we need to sen it to the app server.
        sendRegistrationToServer(refreshedToken);
    }

    private void sendRegistrationToServer(String refreshedToken) {
        // This method currentlyy empty, but if you are required to use server to store information on the server then its useful.
    }
}
